tutoWelcomeBundle_whoami:
    pattern: /qui-suis-je/{name}
    defaults: { _controller: tutoWelcomeBundle:Homepage:whoAmI }
    requirements:
      name: \w+

tutoWelcomeBundle_homepage:
    pattern:  /
    defaults: { _controller: tutoWelcomeBundle:Homepage:index }

tutoWelcomeBundle_contact:
    pattern: /contact
    defaults: { _controller: tutoWelcomeBundle:Contact:contact }

tutoWelcomeBundle_article:
        resource: "@tutoWelcomeBundle/Resources/config/routing/article.yml"
        prefix:   /article

tutoWelcomeBundle_crud:
    resource: "routing/article.yml"
    prefix:   /crud